version: "3"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    restart: always
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server
    depends_on:
      - postgresql
      - mosquitto
    networks:
      default:

  chirpstack-application-server:
    image: chirpstack/chirpstack-application-server:3
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./configuration/chirpstack-application-server:/etc/chirpstack-application-server
    depends_on:
      - chirpstack-network-server
    networks:
      default:
      chirpstack-external:

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    restart: always
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge
    depends_on: 
      - mosquitto
    networks:
      default:

  postgresql:
    image: postgres:9.6-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    networks:
      default:

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redisdata:/data
    networks:
      default:

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    ports:
      - 1883:1883
    volumes: 
      - ./configuration/eclipse-mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      default:

networks:
  default:
  chirpstack-external:
    name: "chirpstack-external"

volumes:
  postgresqldata:
  redisdata:
